--DROP TABLE TestMaster

CREATE TABLE TestMaster
( ID INT IDENTITY(1,1)
, _TestIDOrig VARCHAR(MAX) 
,TestCode VARCHAR(MAX) 
,Testname VARCHAR(MAX) 
,Price VARCHAR(MAX) 
,TotalPrice VARCHAR(MAX) 
,Specimen VARCHAR(MAX) 
,Method VARCHAR(MAX) 
,Schedule VARCHAR(MAX) 
,Reporting VARCHAR(MAX) 
,Units VARCHAR(MAX) 
,IsOutGoingTest VARCHAR(MAX) 
,SubGroupId VARCHAR(MAX) 
,SubGroupType VARCHAR(MAX) 
,IsCulture VARCHAR(MAX) 
,UserId VARCHAR(MAX) 
,EntryDate VARCHAR(MAX) 
,TestIsActive VARCHAR(MAX) 
,TestType VARCHAR(MAX) 
,_SubTestIDOrig VARCHAR(MAX) 
,TestSubType VARCHAR(MAX) 
,[Group] VARCHAR(MAX) 
,SubTestRange VARCHAR(MAX) 
,SubTestUnits VARCHAR(MAX) 
,SubTestIsActive VARCHAR(MAX) 
,ParentSubTestId VARCHAR(MAX) 
,IsHisto VARCHAR(MAX) 
,HistoTestName VARCHAR(MAX) 
,HistoTestType VARCHAR(MAX) 
,TestTitle VARCHAR(MAX) 
,TestParent VARCHAR(MAX) 
,DefaultResult VARCHAR(MAX) 
,IsDifferentialTest VARCHAR(MAX) 
)